behaviors:
  MoveToGoal:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 5120
      learning_rate: 0.00035
      beta: 0.0025
      epsilon: 0.3
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear

    network_settings:
      normalize: true
      hidden_units: 264
      num_layers: 3

    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 0.99
      gail:
        strength: 0.5
        demo_path: Assets/AircraftPhysics/Example/AirplaneAIDemos

    behavioral_cloning:
      demo_path: Assets/AircraftPhysics/Example/AirplaneAIDemos
      steps: 50000
      strength: 0.5
      
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 500000
    time_horizon: 64
    summary_freq: 50000
    threaded: false
    self_play: null
    behavioral_cloning: null