behaviors:
  AirplaneAI:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 5120
      learning_rate: 0.00035
      beta: 0.0025
      epsilon: 0.3
      lambd: 0.95
      num_epoch: 5
      # shared_critic: false
      learning_rate_schedule: linear
      # beta_schedule: linear
      # epsilon_schedule: linear

    network_settings:
      normalize: true
      hidden_units: 264
      num_layers: 3
      # vis_encode_type: simple
      # memory: null
      # goal_conditioning_type: hyper
      # deterministic: false
  
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 0.99
    #   gail:
    #     strength: 0.5
    #     demo_path: C:\Users\jarne\Documents\UnityProjects\Research-Project\AirplaneAIDemos\Demo.demo
    #     use_actions: false

    # behavioral_cloning:
    #   strength: 0.5
    #   demo_path: C:\Users\jarne\Documents\UnityProjects\Research-Project\AirplaneAIDemos\Demo.demo
    #   # steps: 50000
    #   # steps: 750000

    # init_path: null
    keep_checkpoints: 15
    checkpoint_interval: 500000
    max_steps: 50000000
    time_horizon: 264
    summary_freq: 100000
    threaded: true
    # self_play: null